version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: persona_db
      MYSQL_USER: persona_db
      MYSQL_PASSWORD: persona_db
    ports:
      - "3306:3306"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - personapp_network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: persona_db
      MONGO_INITDB_ROOT_PASSWORD: persona_db
    ports:
      - "27017:27017"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - personapp_network

  personapp-cli:
    build:
      context: .
      dockerfile: Dockerfile.cli
    container_name: personapp-cli
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/persona_db
      SPRING_DATASOURCE_USERNAME: persona_db
      SPRING_DATASOURCE_PASSWORD: persona_db
      SPRING_DATA_MONGODB_HOST: mongodb
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: prueba_db
      SPRING_DATA_MONGODB_USERNAME: persona_db
      SPRING_DATA_MONGODB_PASSWORD: persona_db
    depends_on:
      mariadb:
        condition: service_started
      mongodb:
        condition: service_started
    networks:
      - personapp_network

  personapp-rest:
    build:
      context: .
      dockerfile: Dockerfile.rest
    container_name: personapp-rest
    ports:
      - "3000:3000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/persona_db
      SPRING_DATASOURCE_USERNAME: persona_db
      SPRING_DATASOURCE_PASSWORD: persona_db
      SPRING_DATA_MONGODB_HOST: mongodb
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: prueba_db
      SPRING_DATA_MONGODB_USERNAME: persona_db
      SPRING_DATA_MONGODB_PASSWORD: persona_db
    depends_on:
      mariadb:
        condition: service_started
      mongodb:
        condition: service_started
    networks:
      - personapp_network

volumes:
  mariadb_data:
  mongodb_data:

networks:
  personapp_network:
